language: cpp
install:
  - sudo apt-get update -qq
  - sudo apt-get install build-essential libsdl2-dev libsdl2-gfx-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-net-dev libsdl2-ttf-dev
script: cd build; cmake ..; make; make test;
