language: cpp
install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libsdl1.2debian libsdl1.2-dev libsdl-image1.2 libsdl-image1.2-dev libsdl-ttf2.0-0 libsdl-ttf2.0-dev cmake
script: cd build; cmake ..; make; make test;
